import asyncio
from telethon import TelegramClient
from telethon.tl.functions.account import UpdateProfileRequest
from datetime import datetime

# API_ID va API_HASH o'rniga o'z API ma'lumotlaringizni qo'ying
api_id = 'YOUR_API_ID'
api_hash = 'YOUR_API_HASH'

# Telefon raqamingizni kiriting
phone_number = 'YOUR_PHONE_NUMBER'

# TelegramClient yaratish
client = TelegramClient('session_name', api_id, api_hash)

async def update_profile_name():
    await client.start(phone_number)
    while True:
        current_time = datetime.now().strftime('%H:%M')
        await client(UpdateProfileRequest(first_name=current_time))
        print(f'Profile name updated to: {current_time}')
        await asyncio.sleep(60)  # 60 soniya kutish

# Asinxron funksiya ishga tushirish
with client:
    client.loop.run_until_complete(update_profile_name())
